  [[headers]]
     for = "/*.ts"
     [headers.values]
       Content-Type = "application/javascript"

   [[headers]]
     for = "/*.tsx"
     [headers.values]
       Content-Type = "application/javascript"